apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  securityContext:
    runAsUser: 101
    runAsGroup: 300
    fsGroup: 200
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/sh", "-c"] # Commande à exécuter
    args: ["sleep 3600"] # Arguments passés à la commande
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 5
      successThreshold: 1
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 10
  serviceAccountName: my-service-account
  dnsPolicy: ClusterFirst
  restartPolicy: Never
